'use client'
import NavBar from '@/Components/Shared/NavBar/NavBar';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Footer from '@/Components/Shared/Footer/Footer';
import { Provider } from 'react-redux';
import store from './store';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <NavBar></NavBar>
          {children}
          <Footer></Footer>
        </Provider>
      </body>
    </html>
  )
}
